name: stf_dashboard_env
channels:
  - https://repo.anaconda.com/pkgs/snowflake
  - nodefaults
dependencies:
  - python=3.10 # <<< MUDANÇA AQUI: Alterado de 3.11 para 3.10
  - pip
  - pandas
  - openpyxl 
  - streamlit
  - altair
  - bcrypt
  - openai
  # Adicione outras dependências se houver
