name: stf_dashboard_env
channels:
  - https://repo.anaconda.com/pkgs/snowflake
  - nodefaults
dependencies:
  - python=3.11 # <<< MUDANÇA AQUI: Voltando para 3.11
  - pip
  - pandas
  - openpyxl 
  - streamlit
  - altair
  - bcrypt
  - openai
  # Adicione outras dependências se houver
