name: stf_dashboard_env
channels:
  - https://repo.anaconda.com/pkgs/snowflake # Canal principal permitido
  - nodefaults # Necessário para evitar canais padrão indesejados
dependencies:
  - python=3.11 # Mantém a versão do Python
  - pip
  # Lista de pacotes que esperamos encontrar no canal Snowflake:
  - pandas
  - openpyxl 
  - streamlit
  - altair
  - bcrypt
  - openai
  # Adicione outras dependências se houver
